# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Loud & Abrasive: Patrick McVeety-Mill"
email: p.mcvtm@gmail.com
organization: "Loud & Abrasive & Co."
description: > # this means to ignore newlines until "baseurl:"
  Patrick McVeety-Mill's blog and portfolio: Loud & Abrasive.
  Featuring guides, thoughts, and commentary on development, .NET, and more,
  as well as dope art and projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/page/:num/"

#social links
twitter: loudandabrasive
github: pmcvtm
linkedin: pmcvtm
instagram: loudandabrasive
etsy: corrugatedcardbuds

# Build settings
markdown: kramdown
highlighter: rouge
plugins_dir:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
